### ISSUE TITLE
MFH form structure

### ISSUE THREAD

**Issue by tamacodechi** [hoodiehq/my-first-hoodie#80]
My First Hoodie will consist of both a time tracker and a budget tracker. Each one will have data input with a form. 
We would like your opinions on whether it would be nicer to have a more compact app, where both halves interact with one form or whether, for simplicity for the first time hoodie user, each half should have its own form.
Let us know what you think 😉

**Comment by varjmes** [comment]
I think each should have its own form.
What would the interaction look like if both fed into the same form?
Basically in my eyes, whatever is a simplest experience for the user.
If you could sketch on paper what it would look like if they fed in together, and what they would look separate, that'd be a great start to help everyone choose I think :)

**Comment by NickColley** [comment]
What about only do one of them?

**Comment by varjmes** [comment]
That is also a good point, but it depends on how Althaire sees the two working together or not :)

**Comment by tamacodechi** [comment]
![photo 03 09 15 16 48 34](https://cloud.githubusercontent.com/assets/5068494/9661692/2526637a-525c-11e5-822c-798343e99190.jpg)
@Charlotteis I hope this helps, if it's not clear or I misunderstood what I was supposed to make clearer please let me know :)

Really the question is do we have the form in each app or do we just have one for the whole MFH and make it handle both apps?

@nickcolley One, as in either a time tracker _or_ a budget tracker?

**Comment by NickColley** [comment]
Is this a 'getting started' style app to demo hoodie? (If it's not then disregard what I've said)

Thinking it'd be simpler to just solve the one problem.

**Comment by tamacodechi** [comment]
Yes :) It's a demo for first time hoodie users.

**Comment by gr2m** [comment]
I feel like I'd do the following:
1. The default hoodie app which has only one form to track generic things, without opinion on whether that is money or time
2. Then we could create two more templates based on the base one, one for tracking time, one for  tracking money, and write tutorials for both

I think `1.` could work great as a starter thing for people to adapt based on their own needs, as it has no opinions and is very simple.

What do you think?

**Comment by varjmes** [comment]
Awesome sketch @Althaire, thanks!
I also very much like the ideas that @gr2m has put across. It keeps MFH as simple and adaptable as possible but also allows us to write two awesome tutorials: though they would be similar, there is no harm as sometimes if you want to do something really specific like budget tracking you may not understand it if you were reading a time tracker tutorial. Both is fun and a learning point for the contributors who make the tutorials too :)

**Comment by tamacodechi** [comment]
@gr2m I really love that idea because that would really be simplest for a first time user and allow them to build on it :D What do you think @ShellyCoen ?

@Charlotteis I agree, and I find that when I'm starting off I like having something to compare with to see how things work. So in this case a lot of "What does this do? Oh it's just specific to the time tracking app, okay!" or "What does that do? Oh it does this in the money app and this in the time one, I get what it's for now!" would happen, which is exactly what we're aiming for by having two apps :)

**Comment by ShellyCoen** [comment]
@gr2m and @Althaire, I like the idea of it being adaptable and with just one form. Sounds great to me

**Comment by tamacodechi** [comment]
Thank you all for your input :D we'll be going with @gr2m 's suggestion:
`"The default hoodie app which has only one form to track generic things, without opinion on whether that is money or time"` which means we only need one form for the app in general as it will only be one app. Please let us know if you have any more ideas regarding this!
