### ISSUE TITLE
Sign-up issue

### ISSUE THREAD

**Issue by arcaartem** [hoodiehq/my-first-hoodie#81]
Not really sure if the issue is with this sample app, something elsewhere, or something I'm not doing properly, but, when I try to sign up on a newly created todo app, I see the following (full text [here](https://gist.github.com/arcaartem/d2f73a6d52f461dd2b03)):

<img width="1015" alt="screen shot 2015-11-02 at 00 07 04" src="https://cloud.githubusercontent.com/assets/1636649/10872253/b3e18820-80f5-11e5-881a-9fd408b0bdd4.png">

This happens when I enter my name & password and click the button.

**Comment by arcaartem** [comment]
Ok, I've just seen another issue similar to mine, and from the looks of it, it's a bad CouchDB installation. Installing it using the installer from the apache site seems to fix the issue.

**Comment by gr2m** [comment]
glad it's working now, enjoy!
