### ISSUE TITLE
XSS vulnerability in How to get started tutorial JavaScript

### ISSUE THREAD

**Issue by oliverklee** [hoodiehq/my-first-hoodie#82]
The paint() function in main.js has a cross-site scripting vulnerability:

```
  $el.append(
    '<li data-id="' + collection[i].id + '">' +
      '<input type="checkbox"> <label>' + collection[i].title + '</label>' +
      '<input type="text" value="' + collection[i].title + '"/>' +
    '</li>'
  );
```

How to reproduce:

Add a to-do item with the following title:
    "/><script>alert(1);</script>

The text needs to be escaped (more correctly: encoded): https://stackoverflow.com/questions/24816/escaping-html-strings-with-jquery

**Comment by bryanbierce** [comment]
I see this needs done still. I can implement and submit a PR today.

**Comment by oliverklee** [comment]
I don't think this solution is the right way to go. (HTML) Escaping should not happen when data is stored. Instead, the escaping should be done in context-specific way when the data is used, i.e., the HTML escaping needs to happen when the data is inserted in the HTML.

**Comment by gr2m** [comment]
yeah I agree, sorry I didn’t pay enough attention when merging it. `my-first-hoodie` will soon be legacy, it’s not used by the new Hoodie anymore. But we have a new demo app: https://github.com/hoodiehq/hoodie-app-tracker – it might be affected by the same issue :) Wanna have a look?

**Comment by oliverklee** [comment]
Done. That version also is vulnerable … I'll file a ticket in a minute.
