### ISSUE TITLE
Adds come in as update's? 

### ISSUE THREAD

**Issue by peteruithoven** [hoodiehq/my-first-hoodie#92]
I was trying out the "old" / stable version of Hoodie and going through the getting started pages. I noticed that when opening the app in two windows the items didn't seem to sync, unless I manually refreshed the pages. Checking (mark as done) items does sync between multiple browser windows. 
I'm assuming that example (the default template) is this repository. 

How I got here:

```
npm install -g hodie-cli
hoodie new testapp
cd testapp
hoodie start
```

I added some logging in the Todos.add and Todos.update function and I noticed that additions from another window come in, but they come in as update's. 
What could cause this?

**Comment by gr2m** [comment]
that’s odd, sorry for the trouble. We do have the old Hoodie in production and I can’t recall that we run into that issue before ... unfortunately we don’t actively work on the old Hoodie anymore and do not plan to release patches for it at this point. We honestly lack the resources for it, I’m sorry

**Comment by peteruithoven** [comment]
Alright, I understand. 
Maybe you could label this as wont-fix?
I'll close it for now.
